### ISSUE TITLE
UI Problems when not displaying end times

### ISSUE THREAD

**Issue by Terence-Chevroulet** [eouia/MMM-Timetable#2]
So your update did fix the overlap problem, but incidentally caused a new one. I think having a way to enable the last end time only would fix that?

Issue : The yellow highlight and white borders stop at the last starting time and not at the end of the schedule

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/17865635/44394330-3b365180-a537-11e8-8d49-db330185307d.png">

**Comment by eouia** [comment]
Hmmm.. My Mirror doesn't represent that case.
How much did you set `refreshInterval`? The timetable re-render itself per `refreshInterval` miliseconds. If you set that value too long, It might look stuck.

**Comment by Terence-Chevroulet** [comment]
My refreshInterval is set to 1000*60, it's the default right? 

And just to be sure, we're talking about this right?

![image](https://user-images.githubusercontent.com/17865635/44415353-86208b00-a570-11e8-8fbf-bc6f5cca5acb.png)

**Comment by eouia** [comment]
Ah! I understand now. Hmmm.. It could not be easy to fix soon.... Maybe I might change the structure of data. Anyway, Now I catch what it means, And I think I can provide a fix next weekend. (I hope)

**Comment by Terence-Chevroulet** [comment]
Thank you! And don't worry about the time it takes to fix, waiting isn't a problem for me, thank you for all the work you put into this!

**Comment by eouia** [comment]
I've fixed. try it.
