### ISSUE TITLE
24h time format

### ISSUE THREAD

**Issue by KinsoKei** [eouia/MMM-Timetable#3]
Hi, 

I tried to use a 24h format for displaying my timetable but couldn't find where to change from AM/PM to 24h format. My first thought was that iT's managed by convertTime but I had trouble understanding what this does. Is there any way to do so right now?
If not would it be possible to add this feature?

**Comment by eouia** [comment]
Use   `timeFormat: "HH:mm"` instead `"hh:mm A"`,

**Comment by KinsoKei** [comment]
Works. Thanks for the fast reply and help!
