### ISSUE TITLE
Timetable configuration ignored (?)

### ISSUE THREAD

**Issue by Haskar** [eouia/MMM-Timetable#5]
I installed the Timetable module today using the default configuration provided. I also slightly adapted the configuration like this: 
```
{
                        //disabled:false,
                        module: "MMM-Timetable",
                        position: "top_center",
                        config: {
                                timeFormat: "HH:mm",
                                height: "200px",
                                width: "75px",
                                mode: "today", // "today", "5days", "7days"
                                refreshInterval: 1000*60,
                                displayEndTime: true, //whether display endTime on timeline or not.
                                schedules: [{
                                        title: "Jennys Stundenplan",
                                        //file: null, // or "test.csv" - comma separated text file. (see `test.csv`)
                                        schedule: [
                                                // [weekday, starttime(24h), endtime(24h), title, subtitle, backgroundColor(optional)]
                                                // weekday : 1 for Monday, 2 for Tuesday, ... 7 for Sunday
                                                [1, "0730", "0900", "Breakfast", "a", "rgba(0,255,0, 0.5)"],
                                                [2, "0730", "0900", "Breakfast", "a", "rgba(0,255,0, 0.5)"],
                                                [3, "0730", "0900", "Breakfast", "a", "rgba(0,255,0, 0.5)"],
                                                [4, "0730", "0900", "Breakfast", "a", "rgba(0,255,0, 0.5)"],
                                                [5, "0730", "0900", "Breakfast", "a", "rgba(0,255,0, 0.5)"],
                                        ]
                                },]
                        }
                },`
```
However, using **both** configurations I get the same result: an **empty** **7days**-timetable (even though "5days" or "today" is configured).

I cannot seem to find the error. 

here are the errorlogs "tailed" during a restart: 
`==> /home/pi/.pm2/pm2.log <==
2019-09-17 16:07:49: Stopping app:mm id:0
2019-09-17 16:07:49: App [mm] with id [0] and pid [2935], exited with code [0] via signal [SIGINT]
2019-09-17 16:07:49: pid=2935 msg=process killed
2019-09-17 16:07:49: Starting execution sequence in -fork mode- for app name:mm id:0
2019-09-17 16:07:49: App name:mm id:0 online

==> /home/pi/.pm2/logs/mm-out-0.log <==

> magicmirror@2.8.0 start /home/pi/MagicMirror
> sh run-start.sh

==> /home/pi/.pm2/logs/mm-error-0.log <==
/home/pi/MagicMirror/node_modules/electron/dist/electron: /lib/arm-linux-gnueabihf/libdbus-1.so.3: no version information available (required by /home/pi/                                        MagicMirror/node_modules/electron/dist/electron)
/home/pi/MagicMirror/node_modules/electron/dist/electron: /lib/arm-linux-gnueabihf/libdbus-1.so.3: no version information available (required by /home/pi/                                        MagicMirror/node_modules/electron/dist/electron)

==> /home/pi/.pm2/logs/mm-out-0.log <==
Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: MMM-forecast-io.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Traffic
Initializing new module helper ...
Module helper loaded: MMM-LocalTransport
No helper found for module: MMM-Timetable.
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Traffic
MMM-Traffic helper started ...
Connecting socket for: MMM-LocalTransport
MMM-LocalTransport helper started ...
Sockets connected & modules started ...
Launching application.

==> /home/pi/.pm2/logs/mm-error-0.log <==
/proc/self/exe: /lib/arm-linux-gnueabihf/libdbus-1.so.3: no version information available (required by /proc/self/exe)
ATTENTION: default value of option force_s3tc_enable overridden by environment.

==> /home/pi/.pm2/logs/mm-out-0.log <==
Create new calendar fetcher for url: https://service.tuwien.ac.at/ical/?format=ics&lvafrei=1&arbeitsfrei=1&lang=de - Interval: 300000
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/e5ts2v3b2jahfk0uj0s4l65rf8%40group.calendar.google.com/private-a7bfc0840550                                        dbe9fead940919e1da04/basic.ics - Interval: 300000
Create new news fetcher for url: https://www.derstandard.at/rss - Interval: 300000`

Please help me :)

**Comment by eouia** [comment]
Hmmm.. nothing seems wrong.
![image](https://user-images.githubusercontent.com/1720610/65049807-ad5dad80-d966-11e9-9d90-0888dbd63bc2.png)

**Comment by Haskar** [comment]
it looks like this on my mirror :(
<img width="799" alt="2019-09-17_cropped" src="https://user-images.githubusercontent.com/4040699/65050147-35dc4e00-d967-11e9-832f-2d2c5f8d70b8.png">

**Comment by eouia** [comment]
- Backup your current `config.js`
- Make new `config.js`, remove all other modules except `MMM-TimeTable` and `clock` to make things simple.
- Execute MM and let's see what happens.

**Comment by Haskar** [comment]
I now see the same picture you do
Meh ... seems like I have an error somewhere else :) I will try to add one configuration part after the other until it breaks. 

Thanks for the help 👍  :)

**Comment by Haskar** [comment]
Update: Seems like I tempered with the MMM-LocalTransport Module a long time ago, implementing some new config-parameters to show the Transport only on specific days and times. This must have messed up my config. If I copy the MMM-LocalTransport Config to the bottom everything works fine (but thats not how we should do it ... so I fixed it) :)
