### ISSUE TITLE
"invalid date" Error

### ISSUE THREAD

**Issue by Haskar** [eouia/MMM-Timetable#8]
with the newest version I get this error: 
<img width="234" alt="2019-10-22" src="https://user-images.githubusercontent.com/4040699/67269034-2dbb8500-f4b6-11e9-8cde-45fad9576514.png">

using this config: 

```
                        //disabled:false,
                        module: "MMM-Timetable",
                        position: "bottom_left",
                        classes: 'scheduler',
                        config: {
                                timeFormat: "HH:mm",
                                height: "450px",
                                width: "65px",
                                mode: "5days", // "today", "5days", "7days"
                                refreshInterval: 1000*60,
                                displayEndTime: false, //whether display endTime on timeline or not.
                                displayPeriod: true,
                                title: null,
                                module_schedule: {from: '0 6 * * MON-FRI', to: '0 14 * * MON-FRI'},
                                schedules: [{
                                        title: "Jennys Stundenplan",
                                        file: "jenny.csv" // or "test.csv" - comma separated text file. (see `test.csv`)
                                },]
                        }

```

I rolled back to c0fc836

**Comment by eouia** [comment]
could you share me `jenny.csv`? eouia0819@gmail.com

**Comment by Haskar** [comment]
1,0800,0850,3C,"","rgba(0,0,0,0.5)"
1,0855,0945,1C,"","rgba(0,0,0,0.5)"
1,0955,1045,4D,"","rgba(0,0,0,0.5)"
2,1050,1140,1C,"","rgba(0,0,0,0.5)"
2,1150,1240,3C,"","rgba(0,0,0,0.5)"
4,0800,0850,3C,"","rgba(0,0,0,0.5)"
4,1050,1140,4D,"","rgba(0,0,0,0.5)"
4,1150,1240,XSPR,"","rgba(0,0,0,0.5)"
4,1245,1335,1C,"","rgba(0,0,0,0.5)"
5,0800,0850,1C,"","rgba(0,0,0,0.5)"
5,0955,1045,4D,"","rgba(0,0,0,0.5)"

**Comment by eouia** [comment]
I rollback initially. After finding what happens, I'll reroll or add fix.. or wholely new build.

**Comment by Haskar** [comment]
thx :) 

I highly appreciate your quick answers. I could even finish the format in my initial posting and already got an answer. That's awesome!! :)
